# Generated by Django 4.1.7 on 2023-04-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="queue",
            options={"ordering": ["-nomor"]},
        ),
        migrations.AlterModelOptions(
            name="rekammedis",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="queue",
            name="nomor",
            field=models.IntegerField(auto_created=True, editable=False),
        ),
    ]
