# Generated by Django 4.1.7 on 2023-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="name",
        ),
        migrations.AlterField(
            model_name="users",
            name="alamat",
            field=models.TextField(blank=True, null=True, verbose_name="alamat"),
        ),
        migrations.AlterField(
            model_name="users",
            name="jenis_kelamin",
            field=models.CharField(
                choices=[("Laki-Laki", "Laki-Laki"), ("Perempuan", "Perempuan")],
                max_length=255,
                verbose_name="jenis kelamin",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="nik",
            field=models.CharField(max_length=255, unique=True, verbose_name="NIK"),
        ),
        migrations.AlterField(
            model_name="users",
            name="tanggal_lahir",
            field=models.DateField(),
        ),
    ]
