# Generated by Django 4.1.7 on 2023-04-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_queue_options_alter_rekammedis_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="nomor",
            field=models.IntegerField(),
        ),
    ]
